import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";

const Card: React.FC<{
  href?: string;
  title?: string;
  children: React.ReactNode;
}> = ({ href, title, children }) => {
  return (
    <a
      className="m-4 p-6 text-left text-inherit no-underline border border-solid border-[#eaeaea] rounded-[10px] max-w-[300px] hover:text-[#0070f3] hover:border-[#0070f3] focus:text-[#0070f3] focus:border-[#0070f3] active:text-[#0070f3] active:border-[#0070f3] transition-colors"
      href={href}
    >
      <h2 className="m-0 mb-4 text-[1.5rem]">{title}</h2>
      <p className="m-0 text-xl leading-[1.5]">{children}</p>
    </a>
  );
};

const Home: NextPage = () => {
  return (
    <div className="py-0 px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-16 px-0 flex flex-auto flex-col justify-center items-center">
        <h1 className="m-0 leading-[1.15rem] text-[4rem]">
          Welcome to{" "}
          <a
            className="text-[#0070f3] no-underline hover:underline focus:underline active:underline"
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>

        <p className="text-center my-16 mx-0 leading-normal text-2xl">
          Get started by editing{" "}
          <code className="bg-[#fafafa] rounded-[5px] p-3 text-[1.1rem] font-code">
            pages/index.tsx
          </code>
        </p>

        <div className="flex-col w-full flex items-center justify-center flex-wrap sm:flex-row sm:max-w-[800px]">
          <Card href="https://nextjs.org/docs" title="Documentation &rarr;">
            Find in-depth information about Next.js features and API.
          </Card>

          <Card href="https://nextjs.org/learn" title="Learn &rarr;">
            Learn about Next.js in an interactive course with quizzes!
          </Card>

          <Card
            href="https://github.com/vercel/next.js/tree/canary/examples"
            title="Examples &rarr;"
          >
            Discover and deploy boilerplate example Next.js projects.
          </Card>

          <Card
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            title="Deploy &rarr;"
          >
            Instantly deploy your Next.js site to a public URL with Vercel.
          </Card>
        </div>
      </main>

      <footer className="flex flex-auto py-8 px-0 justify-center items-center border-t border-solid border-[#eaeaea]">
        <a
          className="flex justify-center items-center flex-grow"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="h-[1em] ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
