import type { NextPage } from "next";
import Card from "@/components/card";
import Head from "next/head";
import Image from "next/image";
import React from "react";

const Home: NextPage = () => {
  return (
    <div className="py-0 px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-16 px-0 flex flex-auto flex-col justify-center items-center">
        <h1 className="m-0 leading-[1.15rem] text-[4rem]">
          Welcome to{" "}
          <a
            className="text-[#0070f3] no-underline hover:underline focus:underline active:underline"
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>

        <p className="text-center my-16 mx-0 leading-normal text-2xl">
          Get started by editing{" "}
          <code className="bg-[#fafafa] rounded-[5px] p-3 text-[1.1rem] font-code">
            pages/index.tsx
          </code>
        </p>

        <div className="flex-col w-full flex items-center justify-center flex-wrap sm:flex-row sm:max-w-[800px]">
          <Card href="https://nextjs.org/docs">
            <Card.Title>Documentation &rarr;</Card.Title>
            <Card.Desc>
              Find in-depth information about Next.js features and API.
            </Card.Desc>
          </Card>

          <Card href="https://nextjs.org/learn">
            <Card.Title>Learn &rarr;</Card.Title>
            <Card.Desc>
              Learn about Next.js in an interactive course with quizzes!
            </Card.Desc>
          </Card>

          <Card href="https://github.com/vercel/next.js/tree/canary/examples">
            <Card.Title>Examples &rarr;</Card.Title>
            <Card.Desc>
              Discover and deploy boilerplate example Next.js projects.
            </Card.Desc>
          </Card>

          <Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <Card.Title>Deploy &rarr;</Card.Title>
            <Card.Desc>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </Card.Desc>
          </Card>
        </div>
      </main>

      <footer className="flex flex-auto py-8 px-0 justify-center items-center border-t border-solid border-[#eaeaea]">
        <a
          className="flex justify-center items-center flex-grow"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="h-[1em] ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
